### ISSUE TITLE
Workspace ENV not available in workspace packages

### ISSUE THREAD

**Issue by rondonjon** [jeysal/yarn-plugin-dotenv#1]
Not sure if this is a problem with the plugin or with how yarn works in general; sorry in advance if I got it wrong.

I noticed that the ENV vars (stored in an .env file in the workspace directory) are loaded and available when I am running a command on workspace level.

Inside the individual workspace packages however, the variables are not available.

I guess I could now place .env files in each package, but I would prefer not to duplicate them.

Would it be possible to add a fallback to the plugin to load the .env from the workspace level if the plugin was executed in a subpackage without a dedicated .env file?

**Comment by jeysal** [comment]
I suppose looking in parent directories makes sense. It's less about workspaces and individual packages - even when running a workspace script from a random subfolder it fails to use the root `.env`, but yeah. I'll TAL.

**Comment by rondonjon** [comment]
Thanks for fixing this so quickly! I find your plugin super-helpful, great job!

**Comment by cyberwombat** [comment]
@jeysal Im having same issue - but it doesn't seem to have been resolved for me.  Loaded plugin:
```
  - path: .yarn/plugins/@yarnpkg/plugin-dotenv.cjs
    spec: "https://unpkg.com/yarn-plugin-dotenv/bundles/@yarnpkg/plugin-dotenv.js"

```
I have a monorepo with `packages/foo` and a `.env` in the `packages/foo` dir. In that package.json I call a var:
```
"something": "${ENV_VAR}..."
```
And call this from root of workspace using: `yarn workspace foo run something` but that fails with unbound var error.

If I move the .env in root it works

**Comment by jeysal** [comment]
@cyberwombat This issue was about looking for a `.env` file in parent directories from where you run the command. What you're asking for is special behavior for the `yarn workspace` command that also looks in a certain *child* directory (the one of the specified workspace).

I'm not convinced that is worth the effort since it would open a little can of worms. Supporting sub-package `.env` files would mean we also need to support loading multiple `.env` files and merging the variables from the sub-package with those from the root package. I'd rather keep it simple and recommend always putting the `.env` in the root.

**Comment by cyberwombat** [comment]
@jeysal I understand. Thanks for response
